// front-legacy/src/components/navigation-bar/NavigationBarItem.vue
<template>
  <v-sheet
    class="w-100 my-1 d-flex flex-column text-center justify-center align-center navigation-bar-item"
  >
    <v-sheet :width="64" :height="64" class="flex-grow-0 flex-shrink-0">
      <slot></slot>
    </v-sheet>
    <v-sheet class="w-full">{{ label }}</v-sheet>
  </v-sheet>
</template>

<script lang="ts">
export default {
  props: {
    label: {
      type: String,
      required: true,
    },
  },
};
</script>
<style lang="scss" scoped>
.navigation-bar-item {
  cursor: pointer;
}
</style>

// front/src/components/navigation-bar/navigation-bar-item.svelte
<script lang="ts">
  import type { ComponentType } from "svelte";

  export let iconComponent: ComponentType;
  export let label: string;
</script>

<div class="w-full my-1 text-center justify-center cursor-pointer">
  <div class="w-full h-24 flex flex-col">
    <div class="w-full h-16 flex-none">
      <svelte:component this={iconComponent} />
    </div>
    <div class="w-full flex-auto">{label}</div>
  </div>
</div>
