// front-legacy/src/components/lobby/Me.vue
<template>
  <button style="width: 80px; height: 80px">
    <v-sheet
      :height="defaultProfileWidth"
      :width="profileWidth"
      @mouseenter="onMouseEnter"
      @mouseleave="onMouseLeave"
      class="d-flex flex-row align-center profile rounded-pill"
      :class="{ 'elevation-16': isHover }"
    >
      <v-sheet class="flex-grow-0 flex-shrink-0" :width="defaultProfileWidth">
        <v-sheet class="ma-auto" :width="64">
          <UserIcon></UserIcon>
        </v-sheet>
      </v-sheet>
      <v-sheet
        ref="nickname"
        class="flex-grow-0 flex-shrink-0 pr-8 text-h4 font-weight-medium nickname"
        >{{ nickname }}</v-sheet
      >
    </v-sheet>
  </button>
</template>

<script lang="ts">
import UserIcon from "@/icons/UserIcon.vue";
import { VSheet } from "vuetify/lib/components/index.mjs";

export default {
  components: {
    UserIcon,
  },
  props: {
    nickname: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      isHover: false,
      defaultProfileWidth: 80,
      profileWidth: 80,
    };
  },
  watch: {
    isHover(newIsHover) {
      if (!newIsHover) {
        this.profileWidth = this.defaultProfileWidth;
        return;
      }
      let nicknameRef = this.$refs.nickname as VSheet;
      if (!nicknameRef) {
        return;
      }
      this.profileWidth =
        nicknameRef.$el.clientWidth + this.defaultProfileWidth;
    },
  },
  methods: {
    onMouseEnter() {
      this.isHover = true;
    },
    onMouseLeave() {
      this.isHover = false;
    },
  },
};
</script>

<style>
button {
  position: relative;
}

.profile {
  position: absolute;
  overflow: hidden;
  top: 0;
  transition: all 0.3s ease;
}

.profile:hover {
  background-color: var(--primary-200);
}

.nickname {
  display: inline-block;
}
</style>

// front/src/components/lobby/me.svelte
<script lang="ts">
  import UserIcon from "../../icons/user-icon.svelte";

  export let nickname: string = "ROOT#3465";
  let isHover = false;
</script>

<button
  class="w-20 h-20 overflow-visible"
  on:mouseenter={() => {
    isHover = true;
  }}
  on:mouseleave={() => {
    isHover = false;
  }}
>
  <div
    class="h-20 flex gap-2 items-center rounded-full profile"
    class:shadow-2xl={isHover}
  >
    <div class="flex-none w-20">
      <div class="w-16 m-auto">
        <UserIcon></UserIcon>
      </div>
    </div>
    <p class="flex-none pr-8 h2 nickname">{nickname}</p>
  </div>
</button>

<style>
  button {
    position: relative;
  }

  .profile {
    position: absolute;
    z-index: 9998;
    top: 0;
    transition: all 0.3s;
  }

  .profile:hover {
    background-color: var(--tertiary-100);
  }

  .nickname {
    visibility: hidden;
    opacity: 0;
    transition:
      visibility 0.3s,
      opacity 0.3s linear;
  }

  .profile:hover .nickname {
    visibility: visible;
    opacity: 1;
  }
</style>
