// front/src/components/lobby/me.svelte
<script lang="ts">
  import UserIcon from "../../icons/user-icon.svelte";

  export let nickname: string = "ROOT#3465";
  let isHover = false;
</script>

<button
  class="w-20 h-20 overflow-visible"
  on:mouseenter={() => {
    isHover = true;
  }}
  on:mouseleave={() => {
    isHover = false;
  }}
>
  <div
    class="h-20 flex gap-2 items-center rounded-full profile"
    class:shadow-2xl={isHover}
  >
    <div class="flex-none w-20">
      <div class="w-16 m-auto">
        <UserIcon></UserIcon>
      </div>
    </div>
    {#if isHover}
      <p class="flex-none pr-8 h2 nickname">{nickname}</p>
    {/if}
  </div>
</button>

<style>
  button {
    position: relative;
  }

  .profile {
    position: absolute;
    top: 0;
    transition: all 0.3s;
  }

  .profile:hover {
    background-color: var(--tertiary-100);
  }

  .nickname {
    visibility: hidden;
    opacity: 0;
    transition:
      visibility 0.3s,
      opacity 0.3s linear;
  }

  .profile:hover .nickname {
    visibility: visible;
    opacity: 1;
  }
</style>

// front/src/components/lobby/Me.vue
<template>
  <button
    style="width: 80px; height: 80px"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
  >
    <v-sheet
      :height="80"
      class="d-flex flex-row align-center justify-center profile rounded-pill"
      :elevation="16"
    >
      <v-sheet class="flex-grow-0 flex-shrink-0" :width="80">
        <v-sheet class="ma-auto" :width="64">
          <UserIcon></UserIcon>
        </v-sheet>
      </v-sheet>
      <v-sheet
        v-if="isHover"
        class="flex-grow-0 flex-shrink-0 pr-8 text-h4 font-weight-medium nickname"
        >{{ nickname }}</v-sheet
      >
    </v-sheet>
  </button>
</template>

<script lang="ts">
import UserIcon from "@/icons/UserIcon.vue";

export default {
  components: {
    UserIcon,
  },
  props: {
    nickname: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      isHover: false,
    };
  },
  methods: {
    onMouseEnter() {
      this.isHover = true;
    },
    onMouseLeave() {
      this.isHover = false;
    },
  },
};
</script>

<style>
button {
  position: relative;
}

.profile {
  position: absolute;
  top: 0;
  transition: all 0.3s;
}

.profile:hover {
  background-color: var(--tertiary-100);
}
</style>
