// front/src/components/lobby/room-create.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { SlideToggle, Autocomplete } from "@skeletonlabs/skeleton";
  import type { AutocompleteOption } from "@skeletonlabs/skeleton";

  const dispatch = createEventDispatcher();

  let maxRoomCapacity = 20;
  let passwordEnabled = false;
  let name = "";
  let password = "";
  let roomCapacity = 2;
  let playListSearchValue = "";
  let isEnableAutoComplete = false;
  let selectedPlayListId: string | null = null;

  $: isValidName = name.trim().length > 0;
  $: isValidPassword = !passwordEnabled || password.length !== 0;
  $: isValidPlayList = selectedPlayListId !== null;
  $: isValidInput = isValidName && isValidPassword && isValidPlayList;

  let options: AutocompleteOption<string>[] = [
    {
      label: "오늘의 TOP 100: 일본",
      value: "id1",
    },
    {
      label: "오늘의 TOP 100: 한국",
      value: "id2",
    },
    {
      label: "오늘의 TOP 100: 미국",
      value: "id3",
    },
    {
      label: "오늘의 TOP 100: 일본",
      value: "id1",
    },
    {
      label: "오늘의 TOP 100: 한국",
      value: "id2",
    },
    {
      label: "오늘의 TOP 100: 미국",
      value: "id3",
    },
    {
      label: "오늘의 TOP 100: 일본",
      value: "id1",
    },
    {
      label: "오늘의 TOP 100: 한국",
      value: "id2",
    },
    {
      label: "오늘의 TOP 100: 미국",
      value: "id3",
    },
  ];

  function onPlayListSelection(
    event: CustomEvent<AutocompleteOption<string>>,
  ): void {
    playListSearchValue = event.detail.label;
    selectedPlayListId = event.detail.value;
    isEnableAutoComplete = false;
  }
</script>

<div class="card p-12 room-create">
  <header class="card-header p-0 mb-4 h2">방 만들기</header>
  <section>
    <div class="flex flex-col gap-1">
      <div>
        <span>방 이름</span>
        <input
          class="input px-4"
          class:red-border={!isValidName}
          type="text"
          bind:value={name}
          placeholder="1자 이상 입력"
          on:input={() => {
            console.log(name.trim.length);
            console.log(isValidName);
          }}
        />
      </div>
      <div>
        <span>최대 인원수</span>
        <select class="select rounded-full px-4" bind:value={roomCapacity}>
          {#each Array(maxRoomCapacity) as _, index}
            <option value={index + 1}>{index + 1}</option>
          {/each}
        </select>
      </div>
      <div>
        <span>비밀번호</span>
        <div class="flex flex-row gap-2 items-center">
          <SlideToggle
            name="password"
            active="bg-primary-400"
            on:click={() => {
              password = "";
              passwordEnabled = !passwordEnabled;
            }}
            checked={passwordEnabled}
          />
          <input
            class="input px-4"
            class:red-border={!isValidPassword}
            type="password"
            bind:value={password}
            disabled={!passwordEnabled}
          />
        </div>
      </div>
      <div class="relative">
        <span>플레이리스트</span>
        <input
          class="input px-4"
          class:red-border={!isValidPlayList}
          type="search"
          bind:value={playListSearchValue}
          on:input={() => {
            isEnableAutoComplete = true;
            selectedPlayListId = null;
          }}
        />
        {#if isEnableAutoComplete}
          <div
            class="absolute mt-2 card z-20 w-full p-4 overflow-y-auto auto-complete"
          >
            <Autocomplete
              bind:input={playListSearchValue}
              {options}
              filter={() => {
                return options;
              }}
              on:selection={onPlayListSelection}
            />
          </div>
        {/if}
      </div>
    </div>
  </section>
  <footer class="card-footer mt-12 p-0 flex flex-row gap-4">
    <button
      class="btn flex-1 create-button font-bold"
      disabled={!isValidInput}
      on:click={() => {
        console.log(name);
        console.log(passwordEnabled);
        console.log(password);
        console.log(roomCapacity);
      }}>만들기</button
    >
    <button
      class="btn flex-1 cancel-button font-bold"
      on:click={() => dispatch("close")}>취소</button
    >
  </footer>
</div>

<style>
  .room-create {
    background-color: var(--primary-100);
    color: var(--font-light);
  }

  .input {
    background-color: var(--tertiary-50);
    border: solid transparent;
  }

  .select {
    background-color: var(--tertiary-50);
    border: solid transparent;
  }

  .auto-complete {
    background-color: var(--tertiary-50);
  }

  .create-button {
    background-color: var(--primary-300);
    color: var(--font-dark);
  }

  .cancel-button {
    background-color: var(--tertiary-50);
  }

  .red-border {
    border: solid var(--error-300);
  }
</style>

// front/src/components/lobby/RoomCreate.vue
<template>
  <v-sheet class="rounded-lg room-create pa-12">
    <v-sheet class="pa-2 d-flex flex-column ga-2 justify-center">
      <v-sheet class="text-h4 font-weight-bold mb-4">방 만들기</v-sheet>
      <v-form ref="form">
        <v-sheet class="d-flex flex-column ga-1">
          <span>방 이름</span>
          <v-text-field
            v-model="roomName"
            clearable
            variant="solo"
            placeholder="1자 이상 입력"
            bg-color="var(--tertiary-50)"
            base-color="var(--font-dark)"
            color="var(--font-dark)"
            density="compact"
            rounded
            hide-details
            single-line
            flat
            :rules="[isValidRoomName]"
          />
        </v-sheet>
        <v-sheet class="d-flex flex-column ga-1 justify-center">
          <span>최대 인원수</span>
          <v-select
            :items="Array.from({ length: maxRoomCapacity }, (_, i) => i + 1)"
            v-model="selectedRoomCapacity"
            variant="solo"
            bg-color="var(--tertiary-50)"
            base-color="var(--font-dark)"
            density="compact"
            rounded
            hide-details
            single-line
            flat
          >
          </v-select>
        </v-sheet>
        <v-sheet class="d-flex flex-column ga-1 justify-center">
          <span>비밀번호</span>
          <div class="d-flex flex-row ga-2">
            <div>
              <v-switch
                v-model="usePassword"
                @update:model-value="onChangeUsePassword"
                inset
                flat
                density="compact"
                color="var(--primary-450)"
                hide-details
              ></v-switch>
            </div>
            <v-sheet class="d-flex align-center flex-1-1">
              <v-text-field
                v-model="password"
                :disabled="!usePassword"
                type="password"
                clearable
                variant="solo"
                bg-color="var(--tertiary-50)"
                base-color="var(--font-dark)"
                color="var(--font-dark)"
                density="compact"
                rounded
                hide-details
                single-line
                flat
                :rules="[isValidPassword]"
              />
            </v-sheet>
          </div>
        </v-sheet>
        <v-sheet class="d-flex flex-column ga-1 justify-center">
          <span>플레이리스트</span>
          <v-autocomplete
            :items="playlists"
            @update:search="onSearch"
            @update:model-value="onSelect"
            variant="solo"
            bg-color="var(--tertiary-50)"
            base-color="var(--font-dark)"
            class="flex-full-width"
            :custom-filter="customFilter"
            density="compact"
            menu-icon=""
            rounded
            flat
            :rules="[isValidPlaylist]"
          ></v-autocomplete>
        </v-sheet>
        <v-sheet class="d-flex flex-row ga-2 justify-center w-100">
          <v-sheet class="flex-1-1"
            ><v-btn
              block
              rounded
              flat
              variant="tonal"
              :disabled="!isValidForm"
              class="create-button"
              >만들기</v-btn
            ></v-sheet
          >
          <v-sheet class="flex-1-1"
            ><v-btn
              block
              rounded
              flat
              @click="$emit('close')"
              class="cancel-button"
              >취소</v-btn
            ></v-sheet
          >
        </v-sheet>
      </v-form>
    </v-sheet>
  </v-sheet>
</template>

<script lang="ts">
import { VForm } from "vuetify/lib/components/index.mjs";

export default {
  data() {
    return {
      roomName: "",
      maxRoomCapacity: 20,
      selectedRoomCapacity: 1,
      usePassword: false,
      password: "",
      playlists: [] as Array<any>,
      selectedPlaylist: null as number | null,
      searchingId: null as NodeJS.Timeout | null,
    };
  },
  mounted() {
    this.validateForm();
  },
  computed: {
    isValidRoomName() {
      return !!this.roomName && this.roomName.trim().length > 0;
    },
    isValidPassword() {
      return !this.usePassword || (!!this.password && this.password.length > 0);
    },
    isValidPlaylist() {
      return this.selectedPlaylist !== null;
    },
    isValidForm() {
      return (
        this.isValidRoomName && this.isValidPassword && this.isValidPlaylist
      );
    },
  },
  watch: {
    usePassword(newUsePassword) {
      if (!newUsePassword) {
        this.password = "";
      }
    },
  },
  methods: {
    async onSearch() {
      setTimeout(() => {
        if (this.searchingId !== null) {
          clearTimeout(this.searchingId);
        }
        this.searchingId = setTimeout(() => {
          this.playlists = [
            {
              value: 1,
              title: "헉1",
            },
            {
              value: 2,
              title: "헉2",
            },
            {
              value: 3,
              title: "헉3",
            },
            {
              value: 4,
              title: "헉4",
            },
            {
              value: 5,
              title: "헉5",
            },
          ];
        }, 250);
      }, 1000);
    },
    async onSelect(value: any) {
      this.selectedPlaylist = value;
    },
    onChangeUsePassword() {
      this.validateForm();
    },
    customFilter() {
      return true;
    },

    validateForm() {
      let form = this.$refs.form as VForm;
      form?.validate();
    },
  },
};
</script>

<style>
.room-create {
  background-color: var(--primary-100);
}

.v-select__content {
  background-color: var(--tertiary-100);
}

.v-autocomplete__content {
  background-color: var(--tertiary-100);
}

.v-list-item__overlay {
  background-color: #00000000 !important;
}

.v-list-item:hover {
  background-color: var(--tertiary-50);
}

.v-input--disabled .v-field__overlay {
  background-color: #203c3b;
}

.v-input--error .v-field__overlay {
  border: solid var(--error-300);
}

.create-button {
  background-color: var(--primary-300) !important;
  color: var(--font-dark) !important;
}

.create-button .v-btn__underlay {
  background-color: #00000000 !important;
}

.create-button .v-btn__overlay {
  background-color: #00000000 !important;
}

.cancel-button {
  background-color: var(--tertiary-50) !important;
  color: var(--font-light) !important;
}

.cancel-button .v-btn__overlay {
  background-color: #00000000 !important;
}
</style>
