// front-legacy/src/components/lobby/search-input.svelte
<script>
  import SearchIcon from "../../icons/search-icon.svelte";
</script>

<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
  <div class="w-10 pr-2">
    <SearchIcon></SearchIcon>
  </div>
  <input
    class="input"
    type="text"
    placeholder="방 이름, 플레이리스트, 플레이어 이름으로 검색"
  />
</div>

<style>
  .input-group {
    background-color: var(--tertiary-100);
    border: none;
  }
  .input-group div {
    padding-right: 0;
  }
  .input {
    border: none;
  }
</style>

// front-legacy/src/components/lobby/SearchInput.vue
<template>
  <v-sheet class="w-100 rounded-xl search-input">
    <v-text-field
      clearable
      placeholder="방 이름, 플레이리스트, 플레이어 이름으로 검색"
      variant="solo"
      class="w-100 h-100"
      base-color="var(--font-dark)"
      color="var(--font-dark)"
      density="comfortable"
      rounded
      single-line
      hide-details
    >
      <slot:prepend-inner>
        <v-sheet :width="48" :height="24"><SearchIcon></SearchIcon></v-sheet>
      </slot:prepend-inner>
    </v-text-field>
  </v-sheet>
</template>

<script lang="ts">
import SearchIcon from "@/icons/SearchIcon.vue";

export default {
  components: {
    SearchIcon,
  },
};
</script>

<style>
.search-input {
  background-color: var(--primary-450);
  max-width: 1264px;
}
</style>
