// front/src/components/lobby/Me.vue
<template>
  <button
    style="width: 80px; height: 80px"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
  >
    <v-sheet
      :height="80"
      class="d-flex flex-row align-center justify-center profile rounded-pill"
      :elevation="16"
    >
      <v-sheet class="flex-grow-0 flex-shrink-0" :width="80">
        <v-sheet class="ma-auto" :width="64">
          <UserIcon></UserIcon>
        </v-sheet>
      </v-sheet>
      <v-sheet
        v-if="isHover"
        class="flex-grow-0 flex-shrink-0 pr-8 text-h4 font-weight-medium nickname"
        >{{ nickname }}</v-sheet
      >
    </v-sheet>
  </button>
</template>

<script lang="ts">
import UserIcon from "@/icons/UserIcon.vue";

export default {
  components: {
    UserIcon,
  },
  props: {
    nickname: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      isHover: false,
    };
  },
  methods: {
    onMouseEnter() {
      this.isHover = true;
    },
    onMouseLeave() {
      this.isHover = false;
    },
  },
};
</script>

<style>
button {
  position: relative;
}

.profile {
  position: absolute;
  top: 0;
  transition: all 0.3s;
}

.profile:hover {
  background-color: var(--tertiary-100);
}
</style>

// front/app/components/ui/Me.tsx
import { useEffect, useRef, useState } from "react";
import UserIcon from "~/assets/user.svg?react";
import "./Me.css"
import MeStore from "~/stores/MeStore";
import { getRegistrationCode } from "~/utils/registrationCode";

interface MeProperties {
    compact?: boolean;
}

export default function Me({ compact = false }: MeProperties) {
    const me = MeStore((state) => state.me)
    const ensureMe = MeStore((state) => state.ensureMe)

    // compact 조기 반환보다 앞서야 훅 순서가 흔들리지 않는다.
    useEffect(() => {
        ensureMe()
    }, [ensureMe])

    const nicknameRef = useRef<HTMLDivElement>(null);
    const defaultWidth = 56;
    const [width, setWidth] = useState(defaultWidth);
    const [isHover, setHover] = useState(false);

    useEffect(() => {
        if (!isHover) {
            setWidth(defaultWidth);
            return;
        }

        const nicknameRefCurrent = nicknameRef.current
        if (!nicknameRefCurrent) {
            return
        }

        setWidth(nicknameRefCurrent.clientWidth + defaultWidth);
    }, [isHover]);

    if (compact) {
        return (
            <div className="size-[32px] flex items-center justify-center rounded-full bg-zinc-800">
                <UserIcon className="size-[20px]" />
            </div>
        );
    }

    return <>
        <div className="me size-[72px] p-[8px]">
            <div
                className={`h-[56px] flex flex-row items-center align-middle profile transition-all transform rounded-full ${isHover ? "drop-shadow-lg" : ""}`}
                onMouseEnter={ () => setHover(true) }
                onMouseLeave={ () => setHover(false) }
                style={{ width: `${width}px` }}
            >
                <div className={`grow-0 shrink-0 w-[56px] h-[56px] p-[8px] flex`}>
                    <UserIcon className="size-[40px] m-auto"></UserIcon>
                </div>
                <div ref={nicknameRef} className={`grow-0 shrink-0 pr-[36px] my-auto text-3xl align-top nickname`}>
                    <p>{me?.nickname}<span className="text-lg ml-2 text-zinc-400">#{getRegistrationCode(me?.registrationType)}</span></p>
                </div>
            </div>
        </div>
    </>;
}
