// front/src/components/room/players/Player.vue
<template>
  <button class="d-flex flex-row align-center py-1 player">
    <v-avatar :image="photoUrl" size="48"></v-avatar>
    <span class="ml-1 px-1 v-flex flex-row">{{ nickname }}</span>
    <v-sheet :width="16" v-if="isMaster" class="ml-1"
      ><CrownIcon></CrownIcon
    ></v-sheet>
  </button>
</template>

<script lang="ts">
import CrownIcon from "@/icons/CrownIcon.vue";

export default {
  components: {
    CrownIcon,
  },
  props: {
    photoUrl: {
      required: true,
      type: String,
    },
    nickname: {
      required: true,
      type: String,
    },
    isMaster: {
      required: true,
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style>
.player:hover {
  background-color: var(--primary-300);
  color: var(--font-dark);
}

.player:hover svg {
  fill: var(--font-dark);
}
</style>

// front-legacy/src/routes/rooms/[roomId]/player.svelte
<script lang="ts">
  import { Avatar } from "@skeletonlabs/skeleton";
  import CrownIcon from "../../../icons/crown-icon.svelte";

  export let photoUrl: string;
  export let nickname: string;
  export let isMaster = false;

  let isHover = false;
  $: crownColor = isHover ? "--font-dark" : "--font-light";
</script>

<button
  class="flex flex-row items-center cursor-pointer player px-2"
  on:mouseenter={() => {
    isHover = true;
  }}
  on:mouseleave={() => {
    isHover = false;
  }}
>
  <Avatar src={photoUrl} width="w-12" class="flex-none shrink-0"></Avatar>
  <div class="p-1 text-ellipsis overflow-hidden align-middle flex gap-1">
    <span>{nickname}</span>
    {#if isMaster}
      <span class="w-4 flex-none inline-block crown">
        <CrownIcon color={crownColor}></CrownIcon>
      </span>
    {/if}
  </div>
</button>

<style>
  .player:hover {
    background-color: var(--primary-300);
    color: var(--font-dark);
  }
</style>
