// front/src/components/player.svelte
<script>
    import { Avatar } from '@skeletonlabs/skeleton';

    export let photoUrl = "";
    export let nickname = "";
    export let isMaster = false;
</script>

<div class="flex flex-row items-center p-1 cursor-pointer player">
    <Avatar 
        src={photoUrl}
        width="w-12"
        class="p-1 flex-none shrink-0">
    </Avatar>
    <div class="p-1 text-ellipsis overflow-hidden nickname">
        <span>{nickname}</span>
        {#if isMaster}
            <div class="crown p-1.5"></div>
        {/if}
    </div>
</div>

<style>
    .crown {
        background-color: white;
        display: inline-block;
        -webkit-mask: url("/icons/crown.svg") no-repeat center;
        mask: url("/icons/crown.svg") no-repeat center;
    }
    .player:hover {
        background-color: #4ddad6;
    }
</style>

// front-legacy/src/components/room/players/Player.vue
<template>
  <button class="d-flex flex-row align-center py-1 player">
    <v-avatar :image="photoUrl" size="48"></v-avatar>
    <span class="ml-1 px-1 v-flex flex-row">{{ nickname }}</span>
    <v-sheet :width="16" v-if="isMaster" class="ml-1"
      ><CrownIcon></CrownIcon
    ></v-sheet>
  </button>
</template>

<script lang="ts">
import CrownIcon from "@/icons/CrownIcon.vue";

export default {
  components: {
    CrownIcon,
  },
  props: {
    photoUrl: {
      required: true,
      type: String,
    },
    nickname: {
      required: true,
      type: String,
    },
    isMaster: {
      required: true,
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style>
.player:hover {
  background-color: var(--primary-200);
  color: var(--font-light);
}

.player:hover svg {
  fill: var(--font-light);
}
</style>
